version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: irancell_postgres
    restart: always
    environment:
      POSTGRES_USER: irancell_user
      POSTGRES_PASSWORD: SecretPassword123
      POSTGRES_DB: irancell_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build: ./scraper
    container_name: irancell_scraper
    restart: "no"
    depends_on:
      - db
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - db
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  postgres_data:
  grafana-storage:
